- name: deploy tomcat war   
  hosts: webServers1  
  vars:  
  - include: /etc/ansible/roles/webServers1/vars/vars  
  tasks:  
  - name: backup old war    
    shell: cp {{ warRemotePath }}/{{ warName }} {{ warRemotePath }}/{{ warName }}$(date +"%Y%m%d%H%M%S")  
  - name: shutdown tomcat  
    shell: chdir={{ tomcatHome }}/bin ./shutdown.sh && sleep 3
  - name: tomcat down status  
    shell: curl -I http://{{ serverAddress }} &>/dev/null && echo NO || echo YES  
    ignore_errors: True  
    register: isDown
  - name: del old war and dir
    shell: rm -f {{ warRemotePath }}/{{ warName }} && rm -rf {{ warRemotePath }}/{{ warDir }}
    when: isDown.stdout == "YES"  
  - name: rsync war to server  
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}  
  - name: start tomcat  
    shell: chdir={{ tomcatHome }}/bin nohup ./startup.sh &
  - name: sleep 40s
    shell: sleep 40  
  - name: tomcat up status
    shell: curl -I http://{{ serverAddress }} &>/dev/null && echo YES || echo NO  
    ignore_errors: True  
    register: isUp
  - name: show debug info
    debug: var=isUp verbosity=0
