- name: deploy tomcat war   
  hosts: webServers1  
  vars:  
  - include: /etc/ansible/roles/webServers1/vars/vars  
  tasks:  
  - name: backup old war    
    shell: cp {{ warRemotePath }}/{{ warName }} {{ warRemotePath }}/{{ warName }}$(date +"%Y%m%d%H%M%S") 
  - name: del old war and dir
    shell: rm -f {{ warRemotePath }}/{{ warName }} && rm -rf {{ warRemotePath }}/{{ warDir }}
  - name: rsync war to server  
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}  
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest={{ warRemotePath }}/ copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - Restart tomcat
  handlers:  
  - include: /etc/ansible/roles/webServers1/handlers/main.yml
